source : _source/
permalink : /article/:title/
markdown : kramdown
highlighter : pygments

include : []
exclude : ["gulp", "node_modules", "bower", "config.rb", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]

title: "MalaPronta.com / TI"
description: ".."

paginate: 6
comments: true
paginate_path: "/page/:num"

baseurl: ""
url: "http://malapronta.github.io/"
disqus_shortname: fernandomoreira